// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/metrics.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupName    string                 `protobuf:"bytes,1,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	TimeElapsed   int64                  `protobuf:"varint,3,opt,name=time_elapsed,json=timeElapsed,proto3" json:"time_elapsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupMetrics) Reset() {
	*x = BackupMetrics{}
	mi := &file_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupMetrics) ProtoMessage() {}

func (x *BackupMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupMetrics.ProtoReflect.Descriptor instead.
func (*BackupMetrics) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *BackupMetrics) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *BackupMetrics) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupMetrics) GetTimeElapsed() int64 {
	if x != nil {
		return x.TimeElapsed
	}
	return 0
}

type RestoreMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestoreName   string                 `protobuf:"bytes,1,opt,name=restore_name,json=restoreName,proto3" json:"restore_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	TimeElapsed   int64                  `protobuf:"varint,3,opt,name=time_elapsed,json=timeElapsed,proto3" json:"time_elapsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreMetrics) Reset() {
	*x = RestoreMetrics{}
	mi := &file_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreMetrics) ProtoMessage() {}

func (x *RestoreMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreMetrics.ProtoReflect.Descriptor instead.
func (*RestoreMetrics) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreMetrics) GetRestoreName() string {
	if x != nil {
		return x.RestoreName
	}
	return ""
}

func (x *RestoreMetrics) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreMetrics) GetTimeElapsed() int64 {
	if x != nil {
		return x.TimeElapsed
	}
	return 0
}

var File_proto_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrics.proto\x12\rbackupmetrics\x1a\x1bgoogle/protobuf/empty.proto\"m\n" +
	"\rBackupMetrics\x12\x1f\n" +
	"\vbackup_name\x18\x01 \x01(\tR\n" +
	"backupName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\ftime_elapsed\x18\x03 \x01(\x03R\vtimeElapsed\"p\n" +
	"\x0eRestoreMetrics\x12!\n" +
	"\frestore_name\x18\x01 \x01(\tR\vrestoreName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\ftime_elapsed\x18\x03 \x01(\x03R\vtimeElapsed2\xb4\x01\n" +
	"\x14BackupMetricsService\x12N\n" +
	"\x16ReportSuccessfulBackup\x12\x1c.backupmetrics.BackupMetrics\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x13ReportRestoreStatus\x12\x1d.backupmetrics.RestoreMetrics\x1a\x16.google.protobuf.EmptyB$Z\"github.com/oiler-backup/base/protob\x06proto3"

var (
	file_proto_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_proto_rawDescData []byte
)

func file_proto_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_proto_rawDescData
}

var file_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_metrics_proto_goTypes = []any{
	(*BackupMetrics)(nil),  // 0: backupmetrics.BackupMetrics
	(*RestoreMetrics)(nil), // 1: backupmetrics.RestoreMetrics
	(*empty.Empty)(nil),    // 2: google.protobuf.Empty
}
var file_proto_metrics_proto_depIdxs = []int32{
	0, // 0: backupmetrics.BackupMetricsService.ReportSuccessfulBackup:input_type -> backupmetrics.BackupMetrics
	1, // 1: backupmetrics.BackupMetricsService.ReportRestoreStatus:input_type -> backupmetrics.RestoreMetrics
	2, // 2: backupmetrics.BackupMetricsService.ReportSuccessfulBackup:output_type -> google.protobuf.Empty
	2, // 3: backupmetrics.BackupMetricsService.ReportRestoreStatus:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_metrics_proto_init() }
func file_proto_metrics_proto_init() {
	if File_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_proto = out.File
	file_proto_metrics_proto_goTypes = nil
	file_proto_metrics_proto_depIdxs = nil
}
